export interface contentdata{
    comments?: any,
    content?: string,
    headimg?: string,
    id?: string,
    likes?: number,
    name?: string,
    postImages?: string[],
    postVideos?: string[],
    postUserId?: string,
    postTitle?: string,
    postCreateDate?: string,
    markdown?: boolean,
    favorites?: number,
    blog?: string,
}